name: auth_screens
description: "Auth Screens"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
         - asset: assets/fonts/Inter/static/Inter_24pt-Regular.ttf
         - asset: assets/fonts/Inter/static/Inter_24pt-Bold.ttf
           weight: 700
    - family: Lavishly_Yours
      fonts:
         - asset: assets/fonts/Lavishly_Yours/LavishlyYours-Regular.ttf
